#+TITLE: Story Title
#+AUTHOR: Jeff Stautz
#+OPTIONS: toc:nil ':t *:t author:t <:nil num:nil tasks:nil tags:nil title:nil date:nil
#+INCLUDE: ./fiction_header1.org
#+LaTeX_HEADER: \rhead{Stautz / *Story Title* / \thepage}
#+INCLUDE: ./fiction_header2.org

* LaTeX Front Matter (Title, Contact Info, Word Count)

# Modify the title, contact info + word count, but nothing else

\noindent\makebox[\textwidth]{Jeff Stautz \hfill about x,000 words}
\noindent\makebox[\textwidth]{Address Line 1\hfill}
\noindent\makebox[\textwidth]{City, Province, Postal\hfill}
\noindent\makebox[\textwidth]{Canada\hfill}
\noindent\makebox[\textwidth]{Phone\hfill}
\noindent\makebox[\textwidth]{Email\hfill}
\begin{center}
\thispagestyle{empty}
\vspace*{4cm}
\textbf{Story Title}
\end{center}
\begin{doublespace}
\begin{raggedright}
\parindent = 2em

* Manuscript goes here: section one

This is an Emacs org-mode file meant for writing fiction and formatting it for submission to literary magazines, publishers, and agents. 

Replace the author info, contact info, and story title above---both in the =LaTeX_HEADER= lines at the top of the document as well as in the "LaTeX Front Matter" section above. Also remember to update the "about x,000 words" with your word count.

The text of your story goes here, in this section of the doc.

Additional scenes/segments can be added under separate headers, as below.

Use =\vspace{16pt}= to insert a couple of blank lines between sections. Or, if you want, more explicit section breaks with ***s can be inserted with =\sectbreak= like so:

\sectbreak

* Manuscript goes here: section two

Thanks to the =titlesec= package and the =\titleformat= settings above, no org-mode headline titles will appear in the manuscript---add as many sections as you want, and label/title them as you wish.

When writing, =narrow-to-region= within these headlines to focus on a section at a time.

When you want to export, hit =C-c C-e=, choose =l= for LaTeX, then pick an appropriate export format.

The headers and front-matter above should generate a document in standard fiction manuscript format---double-spaced, Times 12, ragged right margins, appropriate headers, contact info on first page.

Leave the following section---containing two lines of LaTeX---in place to close out the double-space / ragged right section.

* End Manuscript

# Do not mofity this section!

\vspace*{-16pt}
\closingbreak

\end{raggedright}
\end{doublespace}

* Notes                                                                         :noexport:

This subtree is for your notes on the story, including raw journal entries.

None of this will get exported to your manuscript when you call =org-export=. So add all the notes and reference material you want down here.

** Characters
** Situation
** Setting
** Themes / Threads
** Outline
** Journal entries
